- AIDevGallery/Samples/Open Source Models/Image Models/ESRGAN/SuperResolution.xaml
- AIDevGallery/Samples/Open Source Models/Image Models/ESRGAN/SuperResolution.xaml.cs
Minor tweaks to the upscaling UX to simplify the XAML a bit.
> Image upscaling sample UX tweaks

- AIDevGallery/Controls/HomePage/Header/HeaderTile/HeaderTile.cs
- AIDevGallery/Controls/HomePage/SampleRow.xaml
- AIDevGallery/Controls/HomePage/SampleRow.xaml.cs
- Fixed accessible names on the homepage flagged by Accessibility Insights
- The "Explore all samples" link now works.
> [a11y] Fixes homepage

- AIDevGallery/Pages/ScenarioSelectionPage.xaml.cs
> [ALLY] 37: Add tooltips to sample navigation menu

- AIDevGallery/Pages/ScenarioPage.xaml.cs
> New button to copy error details if error when exporting projects.

- AIDevGallery/Controls/SampleContainer.xaml.cs
- AIDevGallery/MainWindow.xaml.cs
- AIDevGallery/Models/BaseSampleNavigationParameters.cs
- AIDevGallery/Models/MultiModelSampleNavigationParameters.cs
- AIDevGallery/Models/SampleNavigationParameters.cs
- AIDevGallery/Samples/SharedCode/GenAIModel.cs
> Fixed crash when closing the app and there is a model loading.

- AIDevGallery/Pages/AddModelPage.xaml
Addresses #14 
- replace ScrollViewer + ItemsRepeator with ItemsView
- reduce width of card
> Make the model tiles slightly smaller

- AIDevGallery.Utils/ModelInformationHelper.cs
Fixes an issue (introduced in #5) where if files are in subfolders, then download will fail.
> Fixes download for stable diffusion

- AIDevGallery/Samples/ModelsDefinitions/imagemodels.modelgroup.json
- AIDevGallery/Samples/Open Source Models/Image Models/ESRGAN/SuperResolution.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/FFNet/SegmentStreets.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/ImageNet/ImageClassification.xaml.cs
Added NPU support for:
- SqueezeNet 1.1
- FFNet 54s
- FFNet 78s
- ESRGAN
> Added 4 more NPU QNN image models

- AIDevGallery/ProjectGenerator/Template/App.xaml.cs
- AIDevGallery/ProjectGenerator/Template/MainWindow.xaml.cs
This PR will update templates to use file-scoped namespaces for consistency across all three templates.
> Update the templates to use file-scoped namespaces

- AIDevGallery/Pages/AddModelPage.xaml
- AIDevGallery/Pages/AddModelPage.xaml.cs
Implements: https://github.com/microsoft/ai-dev-gallery/issues/13
> [P2 FEATURE] Add circular progress ring when search is loading

- AIDevGallery/App.xaml
- AIDevGallery/Pages/ScenarioSelectionPage.xaml
- AIDevGallery/Pages/ScenarioSelectionPage.xaml.cs
- AIDevGallery/Styles/Button.xaml
- AIDevGallery/Styles/ComboBox.xaml
Added filter in scenario view to filter to NPU/GPU and eventually WCR APIs
https://github.com/user-attachments/assets/b179978b-c457-4964-bc9a-470d80b5f6ba
> Added filter in scenario view

- AIDevGallery/Samples/Open Source Models/Language Models/CustomSystemPrompt.xaml
> Limits minimum temperature in Custom parameters to 0.01

- .github/workflows/build.yml
- AIDevGallery/ProjectGenerator/Template/ProjectTemplate.csproj
- Directory.Packages.props
Had to rollback. It seems to be an issue with 3.7.x. Working with the testfx team on a fix, but rolled back until we have it.
> Fix test execution.

- AIDevGallery/Pages/ModelPage.xaml.cs
> Fill model family details when model page parameter is ModelDetails

- AIDevGallery/Pages/AddModelPage.xaml
- AIDevGallery/Pages/AddModelPage.xaml.cs
This PR has includes the following changes:
- The searchbox has focus on page load.
- A "No models found" message is shown when no models are found, closing https://github.com/microsoft/ai-dev-gallery/issues/12
- UX revamp:
https://github.com/user-attachments/assets/731b8aa4-7d13-4362-b58d-9efd6b136dd7
> Revamping search models page UX

- AIDevGallery/Controls/HomePage/Header/HeaderCarousel.xaml.cs
Removing the delay and reducing the delay between animations.
Closes https://github.com/microsoft/ai-dev-gallery/issues/74
> Timing tweaks homepage

- AIDevGallery.UnitTests/ProjectGeneratorUnitTests.cs
- AIDevGallery/ProjectGenerator/Generator.cs
- AIDevGallery/ProjectGenerator/Template/MainWindow.xaml.cs
- AIDevGallery/ProjectGenerator/Template/SolutionTemplate.sln
- AIDevGallery/ProjectGenerator/Template/Utils/HardwareAccelerator.cs
- AIDevGallery/Samples/Open Source Models/Language Models/CustomSystemPrompt.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/ExplainCode.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/Generate.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/GenerateCode.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/GrammarCheck.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/Paraphrase.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/SentimentAnalysis.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/Summarize.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/Translate.xaml
> Simplified exported projects.

- AIDevGallery/ProjectGenerator/Generator.cs
> Fix Arm64 GenAI exported projects execution.

- AIDevGallery/Samples/Open Source Models/Image Models/FFNet/SegmentStreets.xaml.cs
- AIDevGallery/Samples/scenarios.json
Fixes #148
Expanded on sample descriptions to add more context and information.
Also renamed Segment Image to Segment Street
> #148: Updated sample descriptions

- AIDevGallery/Samples/WCRAPIs/BackgroundRemover.xaml
- AIDevGallery/Samples/WCRAPIs/BackgroundRemover.xaml.cs
Fixes: #166
Lowered the max points from 32 to 31 because 32 causes a crash.
> Lowered the max points for WCR Remove background

- AIDevGallery/Samples/ModelsDefinitions/apis.json
- AIDevGallery/Samples/WCRAPIs/BackgroundRemover.xaml.cs
- AIDevGallery/Samples/WCRAPIs/ImageDescription.xaml.cs
- AIDevGallery/Samples/WCRAPIs/IncreaseFidelity.xaml.cs
- AIDevGallery/Samples/WCRAPIs/OCRLineSample.xaml.cs
- AIDevGallery/Samples/WCRAPIs/OCRSample.xaml.cs
- AIDevGallery/Samples/scenarios.json
fixes #171 
fixes #172 
fixes #182 
fixes #190
> [WCR] Several fixes related to naming, capitalization, and descriptions

- AIDevGallery/Samples/Open Source Models/Image Models/HRNetPose/PoseDetection.xaml.cs
- AIDevGallery/Samples/SharedCode/PoseHelper.cs
Just did some slight cleaning of Pose sample so that it matches the blog post. No functional or UI changes.
* removed some comments
* simplified some lines
* made variable names clearer
> [REFACTORING] Pose sample cleaning to match blog post

- AIDevGallery/Samples/WCRAPIs/IncreaseFidelity.xaml.cs
> #183: Run image scaling in a task to unblock UI

- AIDevGallery/Pages/ModelPage.xaml.cs
fixes #184 
I believe this captures all types of links in WCR docs
> #184: Fix relative WCR readme links

- AIDevGallery.SourceGenerator/SamplesSourceGenerator.cs
- AIDevGallery/ProjectGenerator/Generator.cs
- AIDevGallery/Samples/Open Source Models/Embeddings/SemanticSearch.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/ESRGAN/SuperResolution.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/FFNet/SegmentStreets.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/Faster RCNN/ObjectDetection.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/HRNetPose/PoseDetection.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/ImageNet/ImageClassification.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/MultiHRNetPose/Multipose.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/YOLOv4/YOLOObjectionDetection.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/ContentModeration.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/CustomSystemPrompt.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/ExplainCode.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/Generate.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/GenerateCode.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/GrammarCheck.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/Paraphrase.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/SentimentAnalysis.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/Summarize.xaml.cs
- AIDevGallery/Samples/Open Source Models/Language Models/Translate.xaml.cs
- AIDevGallery/Samples/Open Source Models/Multimodal Models/DescribeImage.xaml.cs
- AIDevGallery/Samples/Open Source Models/Stable Diffusion/GenerateImage.xaml.cs
- AIDevGallery/Samples/Open Source Models/Whisper/WhisperAudioTranscription.xaml.cs
- AIDevGallery/Samples/Open Source Models/Whisper/WhisperAudioTranslation.xaml.cs
- AIDevGallery/Samples/Open Source Models/Whisper/WhisperLiveTranscription.xaml.cs
- AIDevGallery/Samples/SharedCode/SemanticComboBox.cs
- AIDevGallery/Samples/SharedCode/SmartPasteForm.cs
- AIDevGallery/Samples/SharedCode/SmartTextBox.cs
- AIDevGallery/Telemetry/Events/SampleInteractionEvent.cs
- AIDevGallery/Utils/ModelCache.cs
> Added interaction events on all samples.

- AIDevGallery/Samples/Open Source Models/Multimodal Models/DescribeImage.xaml.cs
- AIDevGallery/Samples/SharedCode/GenAIModel.cs
- Directory.Packages.props
Most notably, this updates ORTGenAI to 0.6.0, which has breaking changes.
> Updated multiple dependencies

- AIDevGallery/Samples/SharedCode/StableDiffusionCode/TextProcessing.cs
Fixes: [#205](https://github.com/microsoft/ai-dev-gallery/issues/205)
Adds a token limit to the Stable Diffusion input box.
> Added a token limit on the stable diffusion input box

- AIDevGallery/Pages/APIs/APIPage.xaml.cs
- AIDevGallery/Samples/SharedCode/WcrApis/WcrModelDownloader.xaml
- AIDevGallery/Samples/WCRAPIs/TextRecognition.xaml.cs
> fixes in wcrmodeldownloader, apipage, and textrecognition

- AIDevGallery/Samples/WCRAPIs/PhiSilicaBasic.xaml.cs
> Stop Phi-Silica Basic

- AIDevGallery/Samples/WCRAPIs/ImageDescription.xaml
- AIDevGallery/Samples/WCRAPIs/ImageDescription.xaml.cs
__Note__: Image Description cannot be canceled before the first word received 
Fixes #239
> Add stop button to Image Description.

- AIDevGallery.UnitTests/ProjectGeneratorUnitTests.cs
- AIDevGallery.UnitTests/UnitTestApp.xaml
> Updated test UI, adding open build folder and open logs buttons.

- AIDevGallery/Controls/WcrModelDownloader.xaml
Removes the background and margin now that the dowloader is not part of the sample
> fix downloader magins and background

- AIDevGallery.SourceGenerator/SamplesSourceGenerator.cs
- AIDevGallery.Utils/SamplesConstants.cs
- AIDevGallery/Controls/SampleContainer.xaml.cs
- AIDevGallery/Helpers/SamplesHelper.cs
- AIDevGallery/ProjectGenerator/Generator.cs
> Refactor the cleaning up of sample files into the source generators, not on project generator.

- AIDevGallery/Samples/Open Source Models/Stable Diffusion/GenerateImage.xaml.cs
> #223: Made error messages in generate image selectable

- AIDevGallery/Helpers/NavigationViewItemHelper.cs
- AIDevGallery/Pages/Scenarios/ScenarioSelectionPage.xaml.cs
> Improve filtering on samples

- AIDevGallery/Controls/HomePage/Header/HeaderCarousel.xaml
Moved the StackPanel containing the hyperlink below the ScrollViewer to resolve the issue where the hyperlink was not clickable. This ensures proper interaction without affecting the visual structure.
Closes #260
> Fix unclickable hyperlink in home page header

- AIDevGallery/Controls/HomePage/GettingStartedSection.xaml
- AIDevGallery/Pages/APIs/APIOverview.xaml
- AIDevGallery/Pages/APIs/APIPage.xaml
- AIDevGallery/Pages/Scenarios/ScenarioOverviewPage.xaml
- AIDevGallery/Styles/Colors.xaml
> Add GH banner to homepage

- AIDevGallery/Pages/Scenarios/ScenarioPage.xaml.cs
> Fixes logic for populating second model dropdown.

- Directory.Packages.props
Updating all dependencies, but SK and MEAI since there are PRs for those already.
> Updated dependencies.

- AIDevGallery.UnitTests/AIDevGallery.UnitTests.csproj
- AIDevGallery.UnitTests/ProjectGeneratorUnitTests.cs
- Directory.Packages.props
Small improvement in test reports.
Also removed Fluent assertions.
> Using dynamic data for test runs.

- AIDevGallery/Controls/ModelSelectionControl.xaml.cs
- AIDevGallery/Pages/Models/ModelSelectionPage.xaml.cs
This PR hides unsupported models in the sample and model view to avoid confusion
> Hide unsupported models

- AIDevGallery/Controls/WcrModelDownloader.xaml.cs
- AIDevGallery/MainWindow.xaml
- AIDevGallery/ProjectGenerator/Template/MainWindow.xaml.cs
- AIDevGallery/Samples/BaseSamplePage.cs
- AIDevGallery/Samples/Definitions/WcrApis/WcrApiCodeSnippet.cs
- AIDevGallery/Samples/Definitions/WcrApis/WcrApiHelpers.cs
- AIDevGallery/Samples/Open Source Models/Language Models/CustomSystemPrompt.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/CustomSystemPrompt.xaml.cs
- AIDevGallery/Samples/SharedCode/IChatClient/PhiSilicaClient.cs
- AIDevGallery/Samples/WCRAPIs/BackgroundRemover.xaml.cs
- AIDevGallery/Samples/WCRAPIs/ImageDescription.xaml.cs
- AIDevGallery/Samples/WCRAPIs/IncreaseFidelity.xaml.cs
- AIDevGallery/Samples/WCRAPIs/LiveImageDescription.xaml.cs
- AIDevGallery/Samples/WCRAPIs/PhiSilicaBasic.xaml.cs
- AIDevGallery/Samples/WCRAPIs/TextRecognition.xaml.cs
- AIDevGallery/Samples/scenarios.json
- AIDevGallery/Styles/Button.xaml
- AIDevGallery/Utils/AppData.cs
- AIDevGallery/Utils/WcrDownloadOperationTracker.cs
- Directory.Packages.props
This version updates the WCR APIs to 1.8 Experimental1
Currently, there is an issue with ImageDescription, __DescribeAsync__ won't describe the image and will return with Status _InternalError__
> Update WCR APIs to 1.8 Experimental1

- AIDevGallery/Telemetry/Events/ModelCacheMovedEvent.cs
- AIDevGallery/Utils/ModelCache.cs
> Simplified model cache moved event

- AIDevGallery/Samples/scenarios.json
Updating Icons for:
- Image Classification
- Remove Object
- Segment Street
- Detect Human Pose
- Detect Multiple pose
- Detect face
> Updating Image Sample Icons

- AIDevGallery/Controls/ModelPicker/ModelOrApiPicker.xaml
- AIDevGallery/Pages/Scenarios/ScenarioPage.xaml
- AIDevGallery/Samples/Open Source Models/Image Models/FFNet/SegmentStreets.xaml
- AIDevGallery/Samples/Open Source Models/Image Models/HRNetPose/PoseDetection.xaml
- AIDevGallery/Samples/Open Source Models/Image Models/ImageNet/ImageClassification.xaml
- AIDevGallery/Samples/Open Source Models/Image Models/MultiHRNetPose/Multipose.xaml
- AIDevGallery/Samples/Open Source Models/Image Models/SINet/DetectBackground.xaml
- AIDevGallery/Samples/Open Source Models/Image Models/YOLOv4/YOLOObjectionDetection.xaml
This PR includes various fixes for the modelpicker and samples to work better on smaller screens
> Samples ux tweaks

- AIDevGallery/Samples/WCRAPIs/PhiSilicaLoRa.xaml.cs
- Directory.Packages.props
Bump MachineLearning NuGet version
> Fix LoRa context

- AIDevGallery/Samples/Definitions/Models/multimodal.modelgroup.json
Fix for this issue: https://github.com/microsoft/ai-dev-gallery/issues/408
As a complementary for this PR: https://github.com/microsoft/ai-dev-gallery/pull/392
> Fix multimodal page crash when using AITK actions

- AIDevGallery/Controls/SampleContainer.xaml
- AIDevGallery/Controls/SampleContainer.xaml.cs
ADO bug report: #54164498
Actual Result:
Narrator is not announcing loading information after selecting any menu item from text drop down in the list.
Expected Result:
Narrator should announce loading information after selecting any menu item from text drop down in the list.
> Fix the accessibility when page loading model

- AIDevGallery/Samples/WCRAPIs/TextRecognition.xaml.cs
> Fix #410 by ensuring rendered text has at least 1pt height

- .pipelines/templates/build.yaml
- docs/Configuring-LAF-Environment-Variables.md
Add Configuring-LAF-Environment-Variables.md
> [Doc]Add Configuring-LAF-Environment-Variables.md
