microsoft/ai-dev-gallery

- AIDevGallery/Samples/Open Source Models/Language Models/Chat.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/Chat.xaml.cs
This pull request improves the chat UI by adding icons, managing input behavior, and adjusting layout interactions; the main changes are:
- Added icons for Send and Stop buttons.
- Disabled sending when the input box is empty or contains only white spaces.
- Disabled the input box while a response is in progress to prevent multiple messages being sent simultaneously.
- Trimmed prompted text to remove unnecessary leading and trailing white spaces.
- Enabled new line insertion with Shift + Enter, set a maximum height for the input box, and enabled scrolling when needed.
- Adjusted the padding of the ScrollViewer in InvertedListView when the scroll bar is visible.
--
--
--
--
> feat(Chat): Enhance input and UI interactions

- AIDevGallery/Pages/ScenarioPage.xaml.cs
A line of code has been added that adds a file type filter to the `FolderPicker` object. The added line is `picker.FileTypeFilter.Add("*");`, which allows the folder picker to accept all file types. Closes #53
> Add File Type Filter to FolderPicker

- AIDevGallery/Samples/ModelsDefinitions/imagemodels.modelgroup.json
Very minor fix - FFNet docs link was pointing to the Pose repo
> [FIX] Fix incorrect docs link for FFNet

- AIDevGallery/Controls/ModelSelectionControl.xaml.cs
- AIDevGallery/Pages/ScenarioPage.xaml
- AIDevGallery/Pages/ScenarioPage.xaml.cs
fixes #81 
Manually closing dialog when visual states change when a model becomes available.
Also updated name of that control to remove some ambiguity.
> #81: Having download dialog open when model finishes downloaded causes app to become uninteractable

- AIDevGallery.SourceGenerator/SamplesSourceGenerator.cs
- AIDevGallery/Models/Samples.cs
- AIDevGallery/ProjectGenerator/Generator.cs
- AIDevGallery/Samples/Attributes/GallerySampleAttribute.cs
- AIDevGallery/Samples/Open Source Models/Image Models/FFNet/SegmentStreets.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/Faster RCNN/ObjectDetection.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/HRNetPose/PoseDetection.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/ImageNet/ImageClassification.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/MultiHRNetPose/Multipose.xaml.cs
- AIDevGallery/Samples/Open Source Models/Image Models/YOLOv4/YOLOObjectionDetection.xaml.cs
Fixes #51 
Just made it so sample asset files are copied over on project export.
@azchohfi should probably look at this one since I was messing with the generator stuff.
> #51: Copy over sample specific asset files to exported samples

- AIDevGallery/Samples/SharedCode/StableDiffusionCode/VaeDecoder.cs
Fixes: https://github.com/microsoft/ai-dev-gallery/issues/110
We were disposing a tensor and then trying to later access it. Cloning the tensor locks it in memory.
> Fix to stable diffusion GPU issue

- .github/workflows/build.yml
- .pipelines/templates/build.yaml
- Directory.Build.props
There is a bug on WinAppSDK if selfcontained is turned on for both the main app and the tests, so we build self contained only on the main build, and not for the tests.
> Enabled self-contained builds when using preview versions of WinAppSDK.

- AIDevGallery/Samples/Open Source Models/Embeddings/RetrievalAugmentedGeneration.xaml
- AIDevGallery/Samples/Open Source Models/Embeddings/RetrievalAugmentedGeneration.xaml.cs
fixes #125 
fixes #128 
Summary of changes:
* Removed RAG indexing progress indicator as it wasn't updating the UI properly, only takes 5-10 seconds, and complicates the sample to have it in there
* Added a "Select PDF" button to the prompting view to allow users to select a new PDF without reloading the sample
* Moved key functions up in the source so that viewing the code shows you `IndexPDF()` and `DoRAG()` towards the top of the file.
> #128 and #125: RAG Improvements

- AIDevGallery/Controls/HomePage/Header/AnimatedImage.xaml
- AIDevGallery/Controls/HomePage/Header/AnimatedImage.xaml.cs
- AIDevGallery/Controls/HomePage/Header/HeaderCarousel.xaml
- AIDevGallery/Controls/HomePage/Header/HeaderCarousel.xaml.cs
- Fixing a bug where some tiles were still in a scaled state when switching windows.
- Tiles will now also be selected and animate when selected with TAB key
> Carousel UX bugfixes

- AIDevGallery/App.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/SmartText.xaml
- AIDevGallery/Samples/Open Source Models/Language Models/SmartText.xaml.cs
- AIDevGallery/Samples/SharedCode/SmartTextBox.cs
- AIDevGallery/Samples/SharedCode/SmartTextBox.xaml
- AIDevGallery/Samples/scenarios.json
fixes #131 
Added smart text box control sample.
> [SAMPLE] Smart Text Box control

- AIDevGallery/Controls/HomePage/SamplesCarousel.xaml.cs
- AIDevGallery/Samples/scenarios.json
fixes #150 
Naively going until the first period of the description, but I don't see these descriptions ever being anything but very plain english, so should be fine.
Also made some description wording more consistent
> #150: Only display first sentence of description for recently used models view

- AIDevGallery/Controls/SampleContainer.xaml.cs
- AIDevGallery/Models/BaseSampleNavigationParameters.cs
- AIDevGallery/Models/MultiModelSampleNavigationParameters.cs
- AIDevGallery/Models/SampleNavigationParameters.cs
- AIDevGallery/Samples/BaseSamplePage.cs
- AIDevGallery/Samples/Open Source Models/Language Models/Chat.xaml.cs
- AIDevGallery/Telemetry/Events/SampleInteractionEvent.cs
TODO: add to other samples after initial review.
> Added sample interaction telemetry event.

- AIDevGallery/Pages/ModelPage.xaml.cs
Fixes: [#185](https://github.com/microsoft/ai-dev-gallery/issues/185)
Problem: [!IMPORTANT], [!TIP], [!NOTE] are Microsoft docs specific markdown callouts. Github flavored md doesn't recognize these callouts.
Fix: use regex to replace the broken callouts
> Added regex to replace MS Docs specific md callouts

- .vsconfig
- AIDevGallery/ProjectGenerator/Generator.cs
- AIDevGallery/ProjectGenerator/Template/.vsconfig
This ensures the WinUI application development workload is suggested to be installed on generated projects, as well as on the app itself.
> Added .vsconfig to AIDevGallery, and to exported projects.

- AIDevGallery/Controls/ModelSelectionControl.xaml
> Icon has an a11y name, fixes a11y bug

- AIDevGallery/Controls/SampleContainer.xaml
- AIDevGallery/Samples/SharedCode/WcrApis/WcrModelDownloader.xaml
- AIDevGallery/Samples/WCRAPIs/BackgroundRemover.xaml
- AIDevGallery/Samples/WCRAPIs/ImageDescription.xaml
- AIDevGallery/Samples/WCRAPIs/IncreaseFidelity.xaml
- AIDevGallery/Samples/WCRAPIs/TextRecognition.xaml
- Minor styling tweaks (rounded corners on all images for WCR samples, WCR download/error/requirements dialog is not covering the entire samplecontainer)
- Closing by using a brush that is meant to be used for UI controls on top of images, so it should meet contrast requirements: https://github.com/microsoft/ai-dev-gallery/issues/230
Light:
> Tweaks to WCR samples UX

- AIDevGallery/Samples/Open Source Models/Embeddings/RetrievalAugmentedGeneration.xaml
- AIDevGallery/Samples/Open Source Models/Embeddings/RetrievalAugmentedGeneration.xaml.cs
Somewhat closing: https://github.com/microsoft/ai-dev-gallery/issues/140
- Loading indicator has been added to show that the SLM is processing.
- The PDF pages are now shown inline, and because it's using the new `ScrollView` control it allows for zooming in and out as well (using touchpad gestures, or ctrl+mouse scroll)
> RAG sample UX improvements

- AIDevGallery/Helpers/ActivationHelper.cs
- AIDevGallery/MainWindow.xaml.cs
- AIDevGallery/Pages/APIs/APIPage.xaml
This feels a bit like a band-aid fix.. we should probably refactor the whole navigation and deeplinking code.
For now, this PR fixes the linking to an API page since that was broken + a UI fix for the copylink button positioning
Steps to repro:
- Navigate to a WCR API page like OCR
- Click the copy button
- Paste the link in the run box
- AI Dev Gallery should launch and navigate to the OCR page
Other deeplinks to test:
_aidevgallery://apis/4bcc0137-0e9a-4eda-8096-b235fcb0e98b_
_aidevgallery://scenarios/generate-text_
_aidevgallery://models/phi4mini_
> Fix API deeplinking

- AIDevGallery/Controls/SampleContainer.xaml
- AIDevGallery/Controls/SampleContainer.xaml.cs
Removed pivot and replaced with tabs, added line numbers
> Replaced code viewer in sample view

- AIDevGallery/Pages/Models/ModelPage.xaml.cs
AI Toolkit button was showing incompatible models, instead of the inverse.
> [BUGFIX] AI toolkit validation check fix

- AIDevGallery/ProjectGenerator/Generator.cs
Copying model to output directory no longer throws an exception
> [FIX] Copy model path bug

- AIDevGallery/Samples/SharedCode/StableDiffusionCode/StableDiffusion.cs
- AIDevGallery/Samples/SharedCode/StableDiffusionCode/TextProcessing.cs
- AIDevGallery/Samples/SharedCode/StableDiffusionCode/VaeDecoder.cs
In PR #393 separate StableDiffusionConfig config dupe objects were created for the SD components. Here the config object created in StableDiffusion class is used across all the components.
> [StableDiffusion Sample] Use same SD config object for all SD components

- AIDevGallery.SourceGenerator/Models/AIToolkitAction.cs
- AIDevGallery/Models/Samples.cs
fix the bug in AIToolkitHelper.cs:
**System.Collections.Generic.KeyNotFoundException: 'The given key 'BulkRun' was not present in the dictionary.'**
This PR completes the cleanup of the BulkRun action from the AIToolkitAction enum. Although https://github.com/microsoft/ai-dev-gallery/pull/392 removed BulkRun from AIToolkitActions, some leftover references still exist in the codebase and may lead to runtime errors. This change ensures that all traces of BulkRun are fully removed to prevent unexpected behavior and improve code consistency.
> fix: 'The given key 'BulkRun' was not present in the dictionary.'

- AIDevGallery/Controls/ModelPicker/AddHFModelView.xaml
ADO bug report: #54185570
Actual Result:
Narrator is not announcing disabled information for not supported on the devices models in the Generate Text page.
Expected Result:
Narrator should announce disabled information for not supported on the devices models in the Generate Text page.
> fix warning button narrator bug
